apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.NAME }}
  namespace: {{ .Values.PROJECT }}
  labels:
    chart: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: {{ .Values.NAME }}
  template:
    metadata:
      labels:
        app: {{ .Values.NAME }}
    spec:
      containers: [{  name: "{{ .Values.NAME }}", image: "{{ .Values.IMAGES }}",
                            envFrom: [{secretRef: {name: "{{ .Values.NAME }}"}}],
                            livenessProbe: { exec: {command: ["rabbitmq-health-check"]},
                            initialDelaySeconds: 120, timeoutSeconds: 20},
                            readinessProbe: { initialDelaySeconds: 10, tcpSocket: {port: 4369}, timeoutSeconds: 1},
                            resources: {limits: {memory: "{{ .Values.MEMORY_LIMIT }}"}},
                            ports: [{containerPort: 4369, protocol: TCP },{containerPort: 5671, protocol: TCP },{containerPort: 5672, protocol: TCP },{containerPort: 15671, protocol: TCP },{containerPort: 15672, protocol: TCP },{containerPort: 25672, protocol: TCP }],
                            volumeMounts: [{ mountPath: "/var/lib/rabbitmq", name: "{{ .Values.NAME }}"}],
                            imagePullPolicy: Always }]


      volumes:
        - name: {{ .Values.NAME }}
          persistentVolumeClaim:
            claimName: {{ .Values.NAME }}

