apiVersion: v1
stringData:
  RABBITMQ_CONF_default__user: {{ .Values.USER }}
  RABBITMQ_CONF_default__pass: {{ .Values.PASSWORD }}
kind: Secret
metadata:
  name: {{ .Values.NAME }}
  namespace: {{ .Values.PROJECT }}
type: Opaque



