apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.NAME }}
  namespace: {{ .Values.PROJECT }}
spec:
  host: {{ .Values.DOMAIN }}
  port:
    targetPort: {{ .Values.PORTS }}
  to:
    kind: Service
    name: {{ .Values.NAME }}

