apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.NAME }}
  namespace: {{ .Values.PROJECT }}
  labels:
    chart: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: {{ .Values.NAME }}
  template:
    metadata:
      labels:
        app: {{ .Values.NAME }}
    spec:
      containers: [{name: "{{ .Values.NAME }}", image: "{{ .Values.IMAGES }}",
                            envFrom: [{secretRef: {name: "{{ .Values.NAME }}"}}],
                            livenessProbe: { initialDelaySeconds: 30, tcpSocket: {port: 27017}, timeoutSeconds: 1},
                            readinessProbe: { exec: {command: ["/bin/sh","-i","-c","mongo 127.0.0.1:27017/$MONGODB_DATABASE -u $MONGODB_USER -p $MONGODB_PASSWORD --eval=\"quit()\""]},
                                              initialDelaySeconds: 10, timeoutSeconds: 5},
                            resources: {limits: {memory: "{{ .Values.MEMORY_LIMIT }}"}},
                            ports: [{containerPort: 27017, protocol: TCP }],
                            volumeMounts: [{ mountPath: "/var/lib/mongodb/data", name: "{{ .Values.NAME }}"}],
                            imagePullPolicy: Always }]

      volumes:
        - name: {{ .Values.NAME }}
          persistentVolumeClaim:
            claimName: {{ .Values.NAME }}

