apiVersion: v1
stringData:
  MONGODB_DATABASE: {{ .Values.DATABASE }}
  MONGODB_PASSWORD: {{ .Values.PASSWORD }}
  MONGODB_ADMIN_PASSWORD: {{ .Values.ADMIN_PASSWORD }}
  MONGODB_USER: {{ .Values.USER }}
kind: Secret
metadata:
  name: {{ .Values.NAME }}
  namespace: {{ .Values.PROJECT }}
type: Opaque



