apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.NAME }}
  namespace: {{ .Values.PROJECT }}
  labels:
    chart: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: {{ .Values.NAME }}
  template:
    metadata:
      labels:
        app: {{ .Values.NAME }}
    spec:
      containers: [{  name: "{{ .Values.NAME }}",  image: "{{ .Values.NAME }}",
                            env: [{name: "NEO4J_JAVA_OPTS", value: "-Xms{{ .Values.NEO4J_MEMORY_LIMIT }} -Xmx{{ .Values.NEO4J_MEMORY_LIMIT }}"} ],
                            livenessProbe: { failureThreshold: 3, initialDelaySeconds: 30, periodSeconds: 10, successThreshold: 1, tcpSocket: {port: 7687}, timeoutSeconds: 1},
                            readinessProbe: { failureThreshold: 3, initialDelaySeconds: 30, periodSeconds: 10, successThreshold: 1, tcpSocket: {port: 7687}, timeoutSeconds: 1},
                            ports: [{containerPort: 7474, protocol: TCP },{containerPort: 7473, protocol: TCP },{containerPort: 7687, protocol: TCP }],
                            resources: {limits: {memory: "{{ .Values.MEMORY_LIMIT }}"}},
                            volumeMounts: [{ mountPath: "/var/lib/neo4j/data", name: "{{ .Values.NAME }}" }],
                            imagePullPolicy: Always}]

      volumes:
        - name: {{ .Values.NAME }}
          persistentVolumeClaim:
            claimName: {{ .Values.NAME }}

