apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.NAME }}
  namespace: {{ .Values.PROJECT }}
  labels:
    chart: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: {{ .Values.NAME }}
  template:
    metadata:
      labels:
        app: {{ .Values.NAME }}
    spec:
      containers: [{  name: "{{ .Values.NAME }}", image: "{{ .Values.IMAGES }}",
                            env:  [{name: "KAFKA_CONF_ADVERTISED_LISTENERS", value: "PLAINTEXT://{{ .Values.NAME }}:9092"}],
                            livenessProbe: { failureThreshold: 3, initialDelaySeconds: 120, periodSeconds: 10, successThreshold: 1, tcpSocket: {port: 2181}, timeoutSeconds: 1},
                            readinessProbe: { failureThreshold: 3, initialDelaySeconds: 120, periodSeconds: 10, successThreshold: 1, tcpSocket: {port: 9092}, timeoutSeconds: 1},
                            ports: [{containerPort: 9092, protocol: TCP },{containerPort: 2181, protocol: TCP }],
                            resources: {limits: {memory: "{{ .Values.MEMORY_LIMIT }}"}},
                            volumeMounts: [{ mountPath: "/data", name: "{{ .Values.NAME }}" }],
                            imagePullPolicy: Always }]
      volumes:
        - name: {{ .Values.NAME }}
          persistentVolumeClaim:
            claimName: {{ .Values.NAME }}

