apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: project
  labels:
    chart: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: telkomindonesia/debian:mariadb-10.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3306
        envFrom:
        - secretRef:
            name: mysql
        volumeMounts:
        - name: mysql
          mountPath: /var/lib/mysql/data 
          readOnly: false
      volumes:
        - name: mysql
          persistentVolumeClaim:
            claimName: mysql

