apiVersion: v1
stringData:
  MYSQL_DATABASE: {{ .Values.MYSQL_DATABASE }}
  MYSQL_PASSWORD: {{ .Values.MYSQL_PASSWORD }}
  MYSQL_ROOT_PASSWORD: {{ .Values.MYSQL_ROOT_PASSWORD }}
  MYSQL_USER: {{ .Values.MYSQL_USER }}
kind: Secret
metadata:
  name: {{ .Values.NAME }}
  namespace: {{ .Values.PROJECT }}
type: Opaque
