apiVersion: v1
stringData:
  MYSQL_DATABASE: "db"
  MYSQL_PASSWORD: "password"
  MYSQL_ROOT_PASSWORD: "password"
  MYSQL_USER: "password"
kind: Secret
metadata:
  name: mysql
  namespace: project
type: Opaque
