apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: project
spec:
  type: ""
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
      name: tcp-3306
  selector: 
      app: mysql  

