{{ if eq .Values.env "stage" }}
apiVersion: v1
stringData: {{ .Values.envstage }}
kind: Secret
metadata:
  name: "{{ .Values.nameaplikasi }}"
  namespace: project
type: Opaque
{{ end }}


{{ if eq .Values.env "prod" }}
apiVersion: v1
stringData: {{ .Values.envprod }}
kind: Secret
metadata:
  name: "{{ .Values.nameaplikasi }}"
  namespace: project
type: Opaque
{{ end }}
