apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.NAME }}
  namespace: {{ .Values.PROJECT }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
     requests:
       storage: {{ .Values.CAPACITY }}

