apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: project
  labels:
    chart: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: telkomindonesia/debian:php-7.4-nginx
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
