apiVersion: v1
stringData:
  POSTGRESQL_DATABASE: {{ .Values.DATABASE }}
  POSTGRESQL_PASSWORD: {{ .Values.PASSWORD }}
  POSTGRESQL_ROOT_PASSWORD: {{ .Values.ROOT_PASSWORD }}
  POSTGRESQL_USER: {{ .Values.USER }}
kind: Secret
metadata:
  name: {{ .Values.NAME }}
  namespace: {{ .Values.PROJECT }}
type: Opaque



