apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.NAME }}
  namespace: {{ .Values.PROJECT }}
spec:
  type: ""
  ports:  [{name: "4369-tcp", port: 4369 },
                {name: "5671-tcp", port: 5671 },
                {name: "5672-tcp", port: 5672 },
                {name: "15671-tcp", port: 15671 },
                {name: "15672-tcp", port: 15672 },
                {name: "25672-tcp", port: 25672 }]
  selector: 
      app: {{ .Values.NAME }}  

